import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { useAuth } from "@/hooks/useAuth";
import { apiRequest, queryClient } from "@/lib/queryClient";
import GlobalHeader from "@/components/GlobalHeader";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import { Progress } from "@/components/ui/progress";
import { 
  Award, 
  Target, 
  TrendingUp, 
  BookOpen, 
  CheckCircle,
  Plus,
  Trash2,
  ChevronRight,
  Star,
  Brain,
  Users,
  Code,
  BarChart3
} from "lucide-react";

interface AssessmentData {
  assessmentType: string;
  currentRole: string;
  targetRole: string;
  skillsToAssess: string[];
}

interface SkillRating {
  skill: string;
  level: number;
  assessment: string;
}

export default function SkillsAssessment() {
  const { isAuthenticated, isLoading } = useAuth();
  const { toast } = useToast();
  const [step, setStep] = useState(1);
  const [formData, setFormData] = useState<AssessmentData>({
    assessmentType: "",
    currentRole: "",
    targetRole: "",
    skillsToAssess: [""]
  });
  const [skillRatings, setSkillRatings] = useState<SkillRating[]>([]);
  const [assessment, setAssessment] = useState<any>(null);

  // Fetch existing assessments
  const { data: existingAssessments } = useQuery({
    queryKey: ["/api/skills-assessments"],
    enabled: isAuthenticated,
  });

  // Generate skills assessment mutation
  const generateAssessmentMutation = useMutation({
    mutationFn: async (data: any) => {
      return await apiRequest("POST", "/api/skills-assessments", data);
    },
    onSuccess: (response) => {
      setAssessment(response);
      setStep(4);
      queryClient.invalidateQueries({ queryKey: ["/api/skills-assessments"] });
      toast({
        title: "Assessment Complete",
        description: "Your skills assessment and learning plan are ready!"
      });
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: "Failed to complete assessment. Please try again.",
        variant: "destructive"
      });
    }
  });

  const handleNext = () => {
    if (step === 1) {
      if (!formData.assessmentType || !formData.currentRole) {
        toast({
          title: "Missing Information",
          description: "Please select assessment type and current role.",
          variant: "destructive"
        });
        return;
      }
      setStep(2);
    } else if (step === 2) {
      const validSkills = formData.skillsToAssess.filter(s => s.trim());
      if (validSkills.length === 0) {
        toast({
          title: "Missing Skills",
          description: "Please add at least one skill to assess.",
          variant: "destructive"
        });
        return;
      }
      // Initialize skill ratings
      setSkillRatings(validSkills.map(skill => ({
        skill,
        level: 1,
        assessment: ""
      })));
      setStep(3);
    } else if (step === 3) {
      // Validate skill ratings
      const incompleteRatings = skillRatings.filter(rating => !rating.assessment.trim());
      if (incompleteRatings.length > 0) {
        toast({
          title: "Incomplete Assessment",
          description: "Please provide assessment details for all skills.",
          variant: "destructive"
        });
        return;
      }
      
      // Submit assessment
      const payload = {
        assessmentType: formData.assessmentType,
        currentRole: formData.currentRole,
        targetRole: formData.targetRole,
        skillsToAssess: formData.skillsToAssess.filter(s => s.trim()),
        assessment: skillRatings.map(rating => ({
          ...rating,
          recommendations: [] // Will be generated by AI
        }))
      };
      
      generateAssessmentMutation.mutate(payload);
    }
  };

  const handleBack = () => {
    setStep(Math.max(1, step - 1));
  };

  const addSkill = () => {
    setFormData(prev => ({
      ...prev,
      skillsToAssess: [...prev.skillsToAssess, ""]
    }));
  };

  const removeSkill = (index: number) => {
    setFormData(prev => ({
      ...prev,
      skillsToAssess: prev.skillsToAssess.filter((_, i) => i !== index)
    }));
  };

  const updateSkill = (index: number, value: string) => {
    setFormData(prev => ({
      ...prev,
      skillsToAssess: prev.skillsToAssess.map((skill, i) => i === index ? value : skill)
    }));
  };

  const updateSkillRating = (index: number, field: keyof SkillRating, value: any) => {
    setSkillRatings(prev => prev.map((rating, i) => 
      i === index ? { ...rating, [field]: value } : rating
    ));
  };

  const startNewAssessment = () => {
    setFormData({
      assessmentType: "",
      currentRole: "",
      targetRole: "",
      skillsToAssess: [""]
    });
    setSkillRatings([]);
    setAssessment(null);
    setStep(1);
  };

  const getSkillLevelText = (level: number) => {
    switch (level) {
      case 1: return "Beginner";
      case 2: return "Basic";
      case 3: return "Intermediate";
      case 4: return "Advanced";
      case 5: return "Expert";
      default: return "Unknown";
    }
  };

  const getSkillLevelColor = (level: number) => {
    switch (level) {
      case 1: return "bg-red-100 text-red-800";
      case 2: return "bg-orange-100 text-orange-800";
      case 3: return "bg-yellow-100 text-yellow-800";
      case 4: return "bg-blue-100 text-blue-800";
      case 5: return "bg-green-100 text-green-800";
      default: return "bg-gray-100 text-gray-800";
    }
  };

  if (isLoading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-orange-50 via-white to-yellow-50">
        <GlobalHeader />
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
          <div className="flex items-center justify-center h-64">
            <div className="animate-spin w-8 h-8 border-4 border-orange-600 border-t-transparent rounded-full"></div>
          </div>
        </div>
      </div>
    );
  }

  if (!isAuthenticated) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-orange-50 via-white to-yellow-50">
        <GlobalHeader />
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16 text-center">
          <h1 className="text-4xl font-bold text-gray-900 mb-4">Access Required</h1>
          <p className="text-xl text-gray-600 mb-8">Please log in to access the Skills Assessment.</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-orange-50 via-white to-yellow-50">
      <GlobalHeader />

      {/* Header */}
      <div className="bg-gradient-to-r from-orange-600 to-yellow-600 text-white py-16">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center">
            <div className="flex items-center justify-center mb-4">
              <div className="p-3 bg-white bg-opacity-20 rounded-lg mr-4">
                <Award className="w-8 h-8" />
              </div>
              <h1 className="text-4xl font-bold">Skills Assessment</h1>
            </div>
            <p className="text-xl text-orange-100 max-w-3xl mx-auto">
              Evaluate and improve your professional skills with comprehensive assessments and personalized learning paths.
            </p>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        {/* Progress Indicator */}
        <div className="mb-8">
          <div className="flex items-center justify-between">
            <div className={`flex items-center ${step >= 1 ? 'text-orange-600' : 'text-gray-400'}`}>
              <div className={`w-8 h-8 rounded-full flex items-center justify-center ${step >= 1 ? 'bg-orange-600 text-white' : 'bg-gray-200'}`}>
                1
              </div>
              <span className="ml-2 font-medium">Setup</span>
            </div>
            <ChevronRight className="w-5 h-5 text-gray-400" />
            <div className={`flex items-center ${step >= 2 ? 'text-orange-600' : 'text-gray-400'}`}>
              <div className={`w-8 h-8 rounded-full flex items-center justify-center ${step >= 2 ? 'bg-orange-600 text-white' : 'bg-gray-200'}`}>
                2
              </div>
              <span className="ml-2 font-medium">Skills Selection</span>
            </div>
            <ChevronRight className="w-5 h-5 text-gray-400" />
            <div className={`flex items-center ${step >= 3 ? 'text-orange-600' : 'text-gray-400'}`}>
              <div className={`w-8 h-8 rounded-full flex items-center justify-center ${step >= 3 ? 'bg-orange-600 text-white' : 'bg-gray-200'}`}>
                3
              </div>
              <span className="ml-2 font-medium">Assessment</span>
            </div>
            <ChevronRight className="w-5 h-5 text-gray-400" />
            <div className={`flex items-center ${step >= 4 ? 'text-orange-600' : 'text-gray-400'}`}>
              <div className={`w-8 h-8 rounded-full flex items-center justify-center ${step >= 4 ? 'bg-orange-600 text-white' : 'bg-gray-200'}`}>
                4
              </div>
              <span className="ml-2 font-medium">Results</span>
            </div>
          </div>
        </div>

        {/* Step 1: Assessment Setup */}
        {step === 1 && (
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Target className="w-5 h-5" />
                Assessment Setup
              </CardTitle>
              <CardDescription>
                Choose the type of assessment and provide role information
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div>
                <Label htmlFor="assessmentType">Assessment Type *</Label>
                <Select value={formData.assessmentType} onValueChange={(value) => setFormData(prev => ({ ...prev, assessmentType: value }))}>
                  <SelectTrigger>
                    <SelectValue placeholder="Select assessment type" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="technical">
                      <div className="flex items-center gap-2">
                        <Code className="w-4 h-4" />
                        Technical Skills
                      </div>
                    </SelectItem>
                    <SelectItem value="soft-skills">
                      <div className="flex items-center gap-2">
                        <Users className="w-4 h-4" />
                        Soft Skills
                      </div>
                    </SelectItem>
                    <SelectItem value="leadership">
                      <div className="flex items-center gap-2">
                        <Star className="w-4 h-4" />
                        Leadership Skills
                      </div>
                    </SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div>
                <Label htmlFor="currentRole">Current Role *</Label>
                <Input
                  id="currentRole"
                  value={formData.currentRole}
                  onChange={(e) => setFormData(prev => ({ ...prev, currentRole: e.target.value }))}
                  placeholder="e.g. Software Engineer, Marketing Manager"
                />
              </div>

              <div>
                <Label htmlFor="targetRole">Target Role (Optional)</Label>
                <Input
                  id="targetRole"
                  value={formData.targetRole}
                  onChange={(e) => setFormData(prev => ({ ...prev, targetRole: e.target.value }))}
                  placeholder="e.g. Senior Software Engineer, Product Manager"
                />
              </div>

              <div className="flex justify-end">
                <Button onClick={handleNext} className="bg-gradient-to-r from-orange-600 to-yellow-600 hover:from-orange-700 hover:to-yellow-700">
                  Next Step
                  <ChevronRight className="w-4 h-4 ml-2" />
                </Button>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Step 2: Skills Selection */}
        {step === 2 && (
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Brain className="w-5 h-5" />
                Skills to Assess
              </CardTitle>
              <CardDescription>
                Add the skills you want to evaluate in this assessment
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div>
                <Label className="text-sm font-medium mb-2 block">Skills *</Label>
                <p className="text-sm text-gray-600 mb-3">
                  {formData.assessmentType === 'technical' && "Technical skills like programming languages, frameworks, tools"}
                  {formData.assessmentType === 'soft-skills' && "Soft skills like communication, teamwork, problem-solving"}
                  {formData.assessmentType === 'leadership' && "Leadership skills like team management, strategic thinking, decision making"}
                </p>
                {formData.skillsToAssess.map((skill, index) => (
                  <div key={index} className="flex gap-2 mb-2">
                    <Input
                      value={skill}
                      onChange={(e) => updateSkill(index, e.target.value)}
                      placeholder={
                        formData.assessmentType === 'technical' ? "e.g. React, Python, AWS" :
                        formData.assessmentType === 'soft-skills' ? "e.g. Communication, Time Management" :
                        "e.g. Team Leadership, Strategic Planning"
                      }
                      className="flex-1"
                    />
                    <Button
                      type="button"
                      variant="outline"
                      size="sm"
                      onClick={() => removeSkill(index)}
                    >
                      <Trash2 className="w-4 h-4" />
                    </Button>
                  </div>
                ))}
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  onClick={addSkill}
                  className="mt-2"
                >
                  <Plus className="w-4 h-4 mr-2" />
                  Add Skill
                </Button>
              </div>

              <div className="flex justify-between">
                <Button variant="outline" onClick={handleBack}>
                  Back
                </Button>
                <Button onClick={handleNext} className="bg-gradient-to-r from-orange-600 to-yellow-600 hover:from-orange-700 hover:to-yellow-700">
                  Start Assessment
                  <ChevronRight className="w-4 h-4 ml-2" />
                </Button>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Step 3: Skill Rating */}
        {step === 3 && (
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <BarChart3 className="w-5 h-5" />
                Rate Your Skills
              </CardTitle>
              <CardDescription>
                For each skill, select your proficiency level and provide context
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              {skillRatings.map((rating, index) => (
                <div key={index} className="border border-gray-200 rounded-lg p-4">
                  <div className="mb-4">
                    <h4 className="font-medium text-gray-900 mb-2">{rating.skill}</h4>
                    <div className="space-y-3">
                      <div>
                        <Label className="text-sm font-medium mb-2 block">Proficiency Level</Label>
                        <div className="grid grid-cols-5 gap-2">
                          {[1, 2, 3, 4, 5].map((level) => (
                            <Button
                              key={level}
                              variant={rating.level === level ? "default" : "outline"}
                              size="sm"
                              onClick={() => updateSkillRating(index, 'level', level)}
                              className={rating.level === level ? "bg-orange-600 hover:bg-orange-700" : ""}
                            >
                              {level}
                            </Button>
                          ))}
                        </div>
                        <div className="mt-2">
                          <Badge className={getSkillLevelColor(rating.level)}>
                            {getSkillLevelText(rating.level)}
                          </Badge>
                        </div>
                        <Progress value={rating.level * 20} className="mt-2" />
                      </div>
                      
                      <div>
                        <Label className="text-sm font-medium mb-2 block">
                          Describe your experience with {rating.skill}
                        </Label>
                        <Input
                          value={rating.assessment}
                          onChange={(e) => updateSkillRating(index, 'assessment', e.target.value)}
                          placeholder={`Describe your experience with ${rating.skill}, including projects, years of use, and specific achievements...`}
                        />
                      </div>
                    </div>
                  </div>
                </div>
              ))}

              <div className="flex justify-between">
                <Button variant="outline" onClick={handleBack}>
                  Back
                </Button>
                <Button 
                  onClick={handleNext} 
                  disabled={generateAssessmentMutation.isPending}
                  className="bg-gradient-to-r from-orange-600 to-yellow-600 hover:from-orange-700 hover:to-yellow-700"
                >
                  {generateAssessmentMutation.isPending ? "Generating Assessment..." : "Complete Assessment"}
                  <TrendingUp className="w-4 h-4 ml-2" />
                </Button>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Step 4: Assessment Results */}
        {step === 4 && assessment && (
          <div className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Award className="w-5 h-5" />
                  Your Skills Assessment Results
                </CardTitle>
                <CardDescription>
                  Comprehensive evaluation with personalized recommendations
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="bg-gradient-to-r from-orange-50 to-yellow-50 p-6 rounded-lg">
                  <div className="text-center mb-6">
                    <div className="w-20 h-20 bg-orange-100 rounded-full flex items-center justify-center mx-auto mb-4">
                      <span className="text-3xl font-bold text-orange-600">
                        {assessment.overallScore || Math.round(skillRatings.reduce((sum, rating) => sum + rating.level, 0) / skillRatings.length * 20)}
                      </span>
                    </div>
                    <h3 className="text-xl font-semibold text-gray-900 mb-2">Overall Score</h3>
                    <p className="text-gray-600">Out of 100 points</p>
                  </div>
                  
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div>
                      <h4 className="font-medium text-gray-900 mb-3">Strength Areas</h4>
                      <ul className="space-y-2">
                        {assessment.strengthAreas?.map((area: string, index: number) => (
                          <li key={index} className="flex items-center gap-2">
                            <CheckCircle className="w-4 h-4 text-green-600" />
                            <span className="text-sm text-gray-700">{area}</span>
                          </li>
                        )) || skillRatings.filter(r => r.level >= 4).map((rating, index) => (
                          <li key={index} className="flex items-center gap-2">
                            <CheckCircle className="w-4 h-4 text-green-600" />
                            <span className="text-sm text-gray-700">{rating.skill}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                    
                    <div>
                      <h4 className="font-medium text-gray-900 mb-3">Improvement Areas</h4>
                      <ul className="space-y-2">
                        {assessment.improvementAreas?.map((area: string, index: number) => (
                          <li key={index} className="flex items-center gap-2">
                            <Target className="w-4 h-4 text-orange-600" />
                            <span className="text-sm text-gray-700">{area}</span>
                          </li>
                        )) || skillRatings.filter(r => r.level <= 2).map((rating, index) => (
                          <li key={index} className="flex items-center gap-2">
                            <Target className="w-4 h-4 text-orange-600" />
                            <span className="text-sm text-gray-700">{rating.skill}</span>
                          </li>
                        ))}
                      </ul>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Individual Skill Breakdown */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <BarChart3 className="w-5 h-5" />
                  Skill Breakdown
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  {skillRatings.map((rating, index) => (
                    <div key={index} className="border border-gray-200 rounded-lg p-4">
                      <div className="flex justify-between items-start mb-3">
                        <h4 className="font-medium text-gray-900">{rating.skill}</h4>
                        <Badge className={getSkillLevelColor(rating.level)}>
                          {getSkillLevelText(rating.level)}
                        </Badge>
                      </div>
                      <Progress value={rating.level * 20} className="mb-3" />
                      <p className="text-sm text-gray-600">{rating.assessment}</p>
                      
                      {/* AI Recommendations would go here */}
                      <div className="mt-3 p-3 bg-gray-50 rounded">
                        <h5 className="text-sm font-medium text-gray-900 mb-2">Recommendations:</h5>
                        <ul className="text-sm text-gray-600 space-y-1">
                          <li>• Practice {rating.skill} through hands-on projects</li>
                          <li>• Seek mentorship from experts in {rating.skill}</li>
                          <li>• Consider online courses or certifications</li>
                        </ul>
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>

            {/* Learning Plan */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <BookOpen className="w-5 h-5" />
                  Personalized Learning Plan
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-6">
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                    <div className="text-center p-4 bg-orange-50 rounded-lg">
                      <h4 className="font-medium text-gray-900 mb-2">Short Term (1-3 months)</h4>
                      <ul className="text-sm text-gray-600 space-y-1 text-left">
                        <li>• Focus on immediate skill gaps</li>
                        <li>• Complete online tutorials</li>
                        <li>• Practice basic exercises</li>
                      </ul>
                    </div>
                    <div className="text-center p-4 bg-yellow-50 rounded-lg">
                      <h4 className="font-medium text-gray-900 mb-2">Medium Term (3-6 months)</h4>
                      <ul className="text-sm text-gray-600 space-y-1 text-left">
                        <li>• Build practical projects</li>
                        <li>• Seek advanced training</li>
                        <li>• Get hands-on experience</li>
                      </ul>
                    </div>
                    <div className="text-center p-4 bg-green-50 rounded-lg">
                      <h4 className="font-medium text-gray-900 mb-2">Long Term (6+ months)</h4>
                      <ul className="text-sm text-gray-600 space-y-1 text-left">
                        <li>• Master advanced concepts</li>
                        <li>• Lead projects and teams</li>
                        <li>• Mentor others</li>
                      </ul>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>

            <div className="flex justify-center">
              <Button 
                onClick={startNewAssessment}
                variant="outline"
              >
                Take New Assessment
              </Button>
            </div>
          </div>
        )}

        {/* Previous Assessments */}
        {existingAssessments && existingAssessments.length > 0 && step === 1 && (
          <Card className="mt-8">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Award className="w-5 h-5" />
                Previous Assessments
              </CardTitle>
              <CardDescription>
                Your past skills evaluations and progress
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                {existingAssessments.map((assess: any) => (
                  <div key={assess.id} className="border border-gray-200 rounded-lg p-4">
                    <div className="flex justify-between items-start">
                      <div>
                        <h4 className="font-medium text-gray-900">{assess.assessmentType} Skills</h4>
                        <p className="text-sm text-gray-600">{assess.currentRole}</p>
                        <div className="flex items-center gap-4 mt-2">
                          <Badge className="bg-orange-100 text-orange-800">
                            Score: {assess.overallScore || 'N/A'}
                          </Badge>
                          <span className="text-sm text-gray-500">
                            {assess.assessment?.length || 0} skills assessed
                          </span>
                        </div>
                      </div>
                      <Badge variant="outline" className="text-xs">
                        {new Date(assess.completedAt).toLocaleDateString()}
                      </Badge>
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
}